import { useEffect, useMemo, useState } from 'react'
import { ArrowLeft,ArrowRight,BookOpen,Castle,ChevronLeft,ChevronRight,Coins,Flag,Hammer,HelpCircle,LockKeyhole,LogOut,Pause,Play,RotateCcw,Settings,Shield,Sparkles,Sprout,Swords,Target,Trees,Trophy,UserRound } from 'lucide-react'
import Board3D,{type Cell} from './Board3D'
import brandLogo from '../logo ô quan dựng nước.png'

type Screen='landing'|'profile'|'lobby'|'game'
type Resources={food:number;wood:number;stone:number}
const initialCells=():Cell[]=>['farm','forest','workshop','barracks','tower','farm','forest','workshop','barracks','tower'].map((building,id)=>({id,soldiers:5,building:building as Cell['building'],owner:id<5?'player':'enemy'}))
const lessons=[
 {tag:'BƯỚC 1 / 5',title:'Chào mừng đến chiến trường',text:'Bàn Ô Ăn Quan đã trở thành một vương quốc. Năm vùng gần thuộc Đại Thành; năm vùng xa thuộc địch.',tip:'Kéo chuột để xoay, cuộn để phóng to bàn cờ.'},
 {tag:'BƯỚC 2 / 5',title:'Mỗi người là một quân',text:'Con số trên vùng là số dân hiện có. Khi ban lệnh, toàn bộ dân được rải lần lượt qua các vùng kế tiếp.',tip:'Luật đếm và rải giữ nguyên tinh thần Ô Ăn Quan.'},
 {tag:'BƯỚC 3 / 5',title:'Mỗi vùng một nhiệm vụ',text:'Ruộng tạo lương, rừng lấy gỗ, xưởng tạo đá. Doanh trại và tháp canh bảo vệ Đại Thành.',tip:'Đường rải tốt vừa tạo tài nguyên, vừa giữ phòng tuyến.'},
 {tag:'BƯỚC 4 / 5',title:'Chọn một ô của quân ta',text:'Nhìn hàng 5 ô phía gần Đại Thành. Nhấn trực tiếp vào một ô có người; vòng sáng vàng sẽ xuất hiện quanh ô đó.',tip:'Bắt đầu bằng ô Ruộng lúa ở hàng quân ta.',action:'① NHẤN VÀO Ô RUỘNG LÚA ĐANG NHẤP NHÁY'},
 {tag:'BƯỚC 5 / 5',title:'Ban lệnh Rải Thuận',text:'Ô đã chọn sẽ rải toàn bộ người lần lượt sang các ô kế tiếp. Nút lệnh màu vàng đang sáng ở cạnh dưới màn hình.',tip:'Nhấn đúng nút RẢI THUẬN có mũi tên sang phải.',action:'② NHẤN NÚT RẢI THUẬN MÀU VÀNG'}]

function Brand(){return <div className="brand"><img className="brand-logo" src={brandLogo} alt="Ô Quan: Dựng Nước"/></div>}
function App(){
 const saved=localStorage.getItem('oquan-profile');const [profile,setProfile]=useState<string|null>(saved);const [name,setName]=useState('');const [screen,setScreen]=useState<Screen>('landing');const [showGuide,setShowGuide]=useState(false);const [lesson,setLesson]=useState(0);const [missionOpen,setMissionOpen]=useState(false);const [citadelOpen,setCitadelOpen]=useState(false)
 const [cells,setCells]=useState(initialCells);const [selected,setSelected]=useState<number|null>(null);const [resources,setResources]=useState<Resources>({food:30,wood:20,stone:12});const [turn,setTurn]=useState(1);const [wave,setWave]=useState(1);const [castleHp,setCastleHp]=useState(100);const [enemyHp,setEnemyHp]=useState(100);const [score,setScore]=useState(0);const [message,setMessage]=useState('Chọn một vùng có quân để ban lệnh.');const [history,setHistory]=useState<string[]>(['Bá tánh bắt đầu dựng nghiệp.'])
 useEffect(()=>{if(screen==='lobby')setScreen('landing')},[screen])
 const mission=useMemo(()=>[{title:'Tích cốc phòng cơ',text:'Đưa dân qua Ruộng lúa',reward:'+8 lương',building:'farm'},{title:'Dựng lũy tre xanh',text:'Đưa dân qua Rừng tre',reward:'+6 gỗ',building:'forest'},{title:'Rèn binh giữ cõi',text:'Đưa dân qua Doanh trại',reward:'+10 uy danh',building:'barracks'}][(turn-1)%3],[turn])
 const selectCell=(id:number)=>{setSelected(id);setMessage(`${cells[id].soldiers} người tại vùng này sẵn sàng xuất phát.`);if(showGuide&&lesson===3)setLesson(4)}
 const command=(direction:-1|1)=>{if(selected===null||cells[selected].soldiers===0)return;const next=cells.map(c=>({...c}));let troops=next[selected].soldiers;const moved=troops;next[selected].soldiers=0;let cursor=selected,food=0,wood=0,stone=0,hits=0;while(troops--){cursor=(cursor+direction+10)%10;next[cursor].soldiers++;if(next[cursor].building==='farm')food+=2;if(next[cursor].building==='forest')wood+=2;if(next[cursor].building==='workshop')stone++;if(next[cursor].building===mission.building)hits++}let battle='';const gap=(cursor+direction+10)%10,target=(gap+direction+10)%10;if(next[gap].soldiers===0&&next[target].owner==='enemy'&&next[target].soldiers){const captured=next[target].soldiers;next[target].soldiers=0;next[target].owner='player';setScore(s=>s+captured*5);setEnemyHp(h=>Math.max(0,h-captured*3));battle=` Phục kích thu phục ${captured} quân!`}if(hits){if(mission.building==='farm')food+=8;if(mission.building==='forest')wood+=6;setScore(s=>s+10)}setResources(r=>({food:r.food+food-2,wood:r.wood+wood,stone:r.stone+stone}));setCells(next);setTurn(t=>t+1);setSelected(null);const text=`Rải ${moved} người · +${food} lương · +${wood} gỗ · +${stone} đá.${battle}`;setMessage(text);setHistory(h=>[text,...h].slice(0,5));if(turn%3===0){const defense=next.filter(c=>c.owner==='player'&&(c.building==='tower'||c.building==='barracks')).reduce((n,c)=>n+c.soldiers,0);const damage=Math.max(3,wave*9-defense);setCastleHp(h=>Math.max(0,h-damage));setWave(w=>w+1);setHistory(h=>[`Đợt công thành ${wave}: Đại Thành mất ${damage} HP.`,...h].slice(0,5))}if(showGuide&&lesson===4&&direction===1)setShowGuide(false)}
 const reset=()=>{setCells(initialCells());setSelected(null);setResources({food:30,wood:20,stone:12});setTurn(1);setWave(1);setCastleHp(100);setEnemyHp(100);setScore(0);setMessage('Chọn một vùng có quân để ban lệnh.');setHistory(['Một vận hội mới bắt đầu.'])}
 const createProfile=()=>{const n=name.trim()||'Thành chủ';localStorage.setItem('oquan-profile',n);setProfile(n);setScreen('landing')}
 const enterGame=(tutorial=false)=>{setScreen('game');if(tutorial){setLesson(0);setShowGuide(true)}}
 if(screen==='landing')return <div className="landing screen"><div className="landing-glow"/><nav><Brand/><div className="landing-navlinks"><button>THẾ GIỚI</button><button>LUẬT CHƠI</button><button>BIÊN NIÊN SỬ</button></div><button className="ghost login-button" onClick={()=>profile?enterGame(false):setScreen('profile')}>{profile?'VÀO CHIẾN TRƯỜNG':'ĐĂNG NHẬP'} <ChevronRight/></button></nav><section className="hero"><span className="overline">MỘT HUYỀN THOẠI DÂN GIAN · MỘT CHIẾN TRƯỜNG MỚI</span><h1>RẢI QUÂN<br/><em>DỰNG NƯỚC</em></h1><p>Điều dân, tích lương, dựng thành. Mỗi nước rải định đoạt vận mệnh một giang sơn.</p><div className="hero-actions"><button className="cta" onClick={()=>profile?enterGame(false):setScreen('profile')}><Play/> {profile?'TIẾP TỤC DỰNG NƯỚC':'BẮT ĐẦU DỰNG NƯỚC'}</button><button className="ghost" onClick={()=>{if(profile)enterGame(true);else setScreen('profile')}}><BookOpen/> TÌM HIỂU CÁCH CHƠI</button></div><div className="hero-proof"><span><b>10</b> vùng đất</span><span><b>2</b> thành trì</span><span><b>∞</b> thế cờ</span></div></section><div className="landing-board"><Board3D cells={initialCells()} selected={null} onSelect={()=>{}}/></div><div className="landing-flags" aria-hidden="true"><i/><i/><i/></div><section className="landing-features"><article><Sprout/><div><b>DỰNG NGHIỆP</b><span>Điều dân, tích lương và nuôi lớn từng vùng đất.</span></div></article><article><Shield/><div><b>GIỮ THÀNH</b><span>Dựng phòng tuyến trước từng đợt quân vây hãm.</span></div></article><article><Swords/><div><b>ĐỊNH THẾ CỜ</b><span>Một nước rải đúng lúc có thể đổi vận giang sơn.</span></div></article></section><aside className="daily-strategy"><span>THẾ CỜ HÔM NAY</span><b>“Lấy dân làm gốc,<br/>lấy thế làm thành.”</b><small>Thử thách: giữ Đại Thành qua 5 đợt vây</small></aside><footer><span>PHIÊN BẢN THỬ NGHIỆM</span><i/><span>CHIẾN THUẬT DÂN GIAN VIỆT</span><i/><span>VẠN THẾ CỜ</span></footer></div>
 if(screen==='profile')return <div className="profile-screen screen"><div className="profile-backdrop"><Board3D cells={initialCells()} selected={null} onSelect={()=>{}}/></div><button className="back-link" onClick={()=>setScreen('landing')}><ArrowLeft/> TRỞ VỀ</button><div className="profile-card ornamental"><div className="mini-seal">御</div><span className="overline">TÂN THÀNH CHỦ</span><h1>Khởi tạo hồ sơ</h1><p>Danh hiệu sẽ được khắc vào sử sách và dùng để lưu hành trình dựng nước.</p><label>TÊN HIỆU CỦA NGƯỜI</label><div className="carved-input"><UserRound/><input value={name} onChange={e=>setName(e.target.value)} onKeyDown={e=>e.key==='Enter'&&createProfile()} placeholder="Ví dụ: Minh Chủ" autoFocus/></div><button className="cta full" onClick={createProfile}>KHẮC TÊN VÀO SỬ SÁCH <ChevronRight/></button><small><Shield/> Hồ sơ prototype được lưu an toàn trên trình duyệt này</small></div></div>
 if(screen==='lobby')return <div className="lobby screen"><header><Brand/><div className="lobby-user"><div><span>THÀNH CHỦ</span><b>{profile}</b></div><div className="avatar"><UserRound/></div><button><Settings/></button></div></header><aside className="lobby-nav"><span className="nav-caption">ĐẠI SẢNH</span><button className="active"><Castle/> Tổng quan</button><button><Trophy/> Thành tựu</button><button><BookOpen/> Bách khoa</button><button onClick={()=>setScreen('landing')}><LogOut/> Trở về sảnh</button></aside><main className="lobby-main"><div className="lobby-title"><div><span className="overline">ĐẠI SẢNH THÀNH CHỦ</span><h1>Vận nước trong tay người</h1><p>Chọn chiến cuộc, quản trị giang sơn và viết tiếp sử Việt.</p></div><div className="rank"><span>UY DANH</span><b>{score||450}</b><small>HÀO KIỆT</small></div></div><section className="continue-card ornamental"><div><span className="overline">CHIẾN CUỘC ĐANG CHỜ</span><h2>Giữ vững Đại Thành</h2><p>Lượt {turn} · Đợt công thành {wave} · Thành còn {castleHp} HP</p><button className="cta" onClick={()=>enterGame(false)}><Play/> TIẾP TỤC CHIẾN CUỘC</button></div><Castle/></section><h2 className="section-title">Chọn con đường dựng nước</h2><div className="mode-grid"><button className="mode-card defense-mode" onClick={()=>enterGame(!localStorage.getItem('oquan-trained'))}><Shield/><span>KHẢ DỤNG</span><h3>Thủ Thành</h3><p>Tích lương, bố trí dân binh và chống lại từng đợt vây thành.</p><b>VÀO CHIẾN TRƯỜNG <ChevronRight/></b></button><button className="mode-card locked"><LockKeyhole/><span>SẮP RA MẮT</span><h3>Tranh Hùng</h3><p>Đấu trí cùng Thành chủ khác trên cùng một bàn Ô Quan.</p></button><button className="mode-card locked"><LockKeyhole/><span>SẮP RA MẮT</span><h3>Chiến Dịch</h3><p>Vượt qua các chương sử thi và thống nhất bờ cõi.</p></button></div></main></div>
 return <main className="battle screen"><div className="battle-world"><Board3D cells={cells} selected={selected} onSelect={selectCell}/></div><header className="top-hud hud"><Brand/><div className="resources"><Resource icon={<Sprout/>} label="LƯƠNG" value={resources.food} max={60} color="#6f9339"/><Resource icon={<Trees/>} label="GỖ" value={resources.wood} max={60} color="#a26432"/><Resource icon={<Hammer/>} label="ĐÁ" value={resources.stone} max={60} color="#8c929a"/><div className="prestige"><Coins/><span>UY DANH</span><b>{score}</b></div></div><div className="turn-info"><b>LƯỢT {String(turn).padStart(2,'0')}</b><span>CÔNG THÀNH: {3-((turn-1)%3)} LƯỢT</span></div><button onClick={()=>setShowGuide(true)}><HelpCircle/></button><button onClick={()=>setScreen('lobby')}><Pause/></button><div className="avatar"><UserRound/></div></header>
 <aside className={`battle-left hud panel-frame collapsible ${missionOpen?'open':'compact'}`}><button className="panel-toggle" onClick={()=>setMissionOpen(v=>!v)} title={missionOpen?'Thu gọn nhiệm vụ':'Mở bảng nhiệm vụ'}>{missionOpen?<ChevronLeft/>:<ChevronRight/>}</button>{missionOpen?<><span className="panel-kicker"><Target/> NHIỆM VỤ HIỆN TẠI</span><h2>{mission.title}</h2><p>{mission.text} trước khi địch mở đợt tiến công kế tiếp.</p><div className="mission-progress"><div><span>TIẾN ĐỘ</span><b>{Math.min(100,(turn%3)*34)}%</b></div><i><em style={{width:`${Math.min(100,(turn%3)*34)}%`}}/></i></div><div className="reward-box"><Sparkles/><span>PHẦN THƯỞNG<b>{mission.reward}</b></span></div><hr/><h3>NHIỆM VỤ TIẾP THEO</h3><div className="next-mission"><LockKeyhole/><span>Mở rộng bờ cõi<small>Chiếm một vùng của quân địch</small></span></div></>:<div className="compact-mission"><Target/><span>NHIỆM VỤ<b>{Math.min(100,(turn%3)*34)}%</b></span><i><em style={{height:`${Math.min(100,(turn%3)*34)}%`}}/></i></div>}</aside>
 <aside className={`battle-right hud panel-frame collapsible ${citadelOpen?'open':'compact'}`}><button className="panel-toggle" onClick={()=>setCitadelOpen(v=>!v)} title={citadelOpen?'Thu gọn thành trì':'Mở bảng thành trì'}>{citadelOpen?<ChevronRight/>:<ChevronLeft/>}</button>{citadelOpen?<><span className="panel-kicker"><Castle/> ĐẠI THÀNH</span><div className="citadel"><Castle/><div><b>ĐỘ BỀN THÀNH</b><span>{castleHp}/100</span><i><em style={{width:`${castleHp}%`}}/></i></div></div><div className="siege-alert"><Swords/><span>ĐỢT ĐỊCH KẾ TIẾP<b>Còn {3-((turn-1)%3)} lượt chuẩn bị</b></span></div><h3>NHẬT KÝ CHIẾN TRƯỜNG</h3><div className="battle-log">{history.map((h,i)=><p key={i}><b>[Lượt {Math.max(1,turn-i)}]</b> {h}</p>)}</div><button className="reset-link" onClick={reset}><RotateCcw/> DỰNG LẠI THẾ CỜ</button></>:<div className="compact-health"><div><Castle/><span>TA<b>{castleHp}</b></span><i><em style={{height:`${castleHp}%`}}/></i></div><div className="enemy"><Swords/><span>ĐỊCH<b>{enemyHp}</b></span><i><em style={{height:`${enemyHp}%`}}/></i></div></div>}</aside>
 <div className="selection-hint hud"><span>{selected===null?'CHƯA CHỌN ĐẠO QUÂN':`${cells[selected].soldiers} NGƯỜI SẴN SÀNG`}</span><b>{message}</b></div>
 <nav className="command-dock hud"><button className="dock-minor"><Sparkles/><span>TRẬN PHÁP</span></button><button className="dock-action secondary" disabled={selected===null} onClick={()=>command(-1)}><ArrowLeft/><span>RẢI NGƯỢC</span></button><button className="dock-action primary" disabled={selected===null} onClick={()=>command(1)}><ArrowRight/><span>RẢI THUẬN</span></button><button className="dock-minor danger" onClick={()=>setScreen('lobby')}><Flag/><span>RÚT LUI</span></button></nav>
 {showGuide&&<div className={`guide-layer step-${lesson}`}><div className="guide-card ornamental"><span>{lessons[lesson].tag}</span><h2>{lessons[lesson].title}</h2><p>{lessons[lesson].text}</p><div className="tip"><BookOpen/> {lessons[lesson].tip}</div>{lessons[lesson].action?<b className="guide-action">{lessons[lesson].action}</b>:<button className="cta full" onClick={()=>setLesson(l=>{if(l===2)setSelected(0);return l+1})}>TIẾP TỤC <ChevronRight/></button>}<button className="skip" onClick={()=>{setShowGuide(false);setSelected(null);localStorage.setItem('oquan-trained','true')}}>Bỏ qua hướng dẫn</button></div></div>}
 {(castleHp<=0||enemyHp<=0)&&<div className="result-modal"><div className="ornamental"><Castle/><h2>{enemyHp<=0?'KHẢI HOÀN!':'ĐẠI THÀNH THẤT THỦ'}</h2><p>{enemyHp<=0?'Thế rải quân đã khuất phục địch thành.':'Hãy củng cố doanh trại và tháp canh trước đợt công thành.'}</p><button className="cta" onClick={reset}>DỰNG LẠI CƠ ĐỒ</button></div></div>}</main>
}
function Resource({icon,label,value,max,color}:{icon:React.ReactNode;label:string;value:number;max:number;color:string}){return <div className="resource">{icon}<div><span>{label}</span><i><em style={{width:`${Math.min(100,value/max*100)}%`,background:color}}/></i></div><b>{value}</b></div>}
export default App
