import { useEffect,useMemo,useRef,useState } from 'react'
import { Canvas,useFrame } from '@react-three/fiber'
import { Clone,ContactShadows,Environment,Html,OrbitControls,useGLTF } from '@react-three/drei'
import * as THREE from 'three'
import type { ThreeEvent } from '@react-three/fiber'
import { assetUrl,O_QUAN_ASSETS } from './game3d/assetRegistry'
import { BOARD_LAYOUT,tilePosition,type BoardTile } from './game3d/boardLayout'

type Building='farm'|'forest'|'workshop'|'barracks'|'tower'
export type Cell={id:number;soldiers:number;building:Building;owner:'player'|'enemy'|'neutral'}
const names:Record<Building,string>={farm:'RUỘNG LÚA',forest:'RỪNG TRE',workshop:'XƯỞNG MỘC',barracks:'DOANH TRẠI',tower:'THÁP CANH'}
const dynamic:Record<Building,{role:string;resource:string;action:'work'|'train'|'guard'}>={farm:{role:O_QUAN_ASSETS.characters.farmer,resource:O_QUAN_ASSETS.resources.food,action:'work'},forest:{role:O_QUAN_ASSETS.characters.woodcutter,resource:O_QUAN_ASSETS.resources.bamboo,action:'work'},workshop:{role:O_QUAN_ASSETS.characters.carpenter,resource:O_QUAN_ASSETS.resources.materials,action:'work'},barracks:{role:O_QUAN_ASSETS.characters.soldier,resource:O_QUAN_ASSETS.resources.iron,action:'train'},tower:{role:O_QUAN_ASSETS.characters.guard,resource:O_QUAN_ASSETS.resources.stone,action:'guard'}}

function Model({file,height=1,position=[0,0,0],rotation=[0,0,0]}:{file:string;height?:number;position?:[number,number,number];rotation?:[number,number,number]}){const {scene}=useGLTF(assetUrl(file));const fit=useMemo(()=>{const box=new THREE.Box3().setFromObject(scene),size=new THREE.Vector3(),center=new THREE.Vector3();box.getSize(size);box.getCenter(center);const scale=height/Math.max(size.y,.001);return {scale,offset:[-center.x*scale,-box.min.y*scale,-center.z*scale] as [number,number,number]}},[scene,height]);return <group position={position} rotation={rotation}><Clone object={scene} scale={fit.scale} position={fit.offset} castShadow receiveShadow/></group>}
function Actor({file,position,phase,action,enemy}:{file:string;position:[number,number,number];phase:number;action:'work'|'train'|'guard';enemy:boolean}){const ref=useRef<THREE.Group>(null);useFrame(({clock})=>{if(!ref.current)return;const t=clock.elapsedTime*2.6+phase;ref.current.position.y=position[1]+Math.abs(Math.sin(t))*.035;ref.current.rotation.z=action==='work'?Math.sin(t)*.075:0;ref.current.rotation.y=(enemy?Math.PI:0)+(action==='train'?Math.sin(t)*.08:0)});return <group ref={ref} position={position}><Model file={file} height={.62}/></group>}
function Selection({enemy}:{enemy:boolean}){const ref=useRef<THREE.Mesh>(null);useFrame(({clock})=>{if(ref.current){const s=1+Math.sin(clock.elapsedTime*3)*.035;ref.current.scale.setScalar(s)}});return <mesh ref={ref} position={[0,.37,0]} rotation={[-Math.PI/2,0,0]}><ringGeometry args={[1.05,1.12,64]}/><meshBasicMaterial color={enemy?'#d95548':'#f2b84b'} transparent opacity={.92}/></mesh>}
function DynamicOccupants({cell}:{cell:Cell}){const cfg=dynamic[cell.building],enemy=cell.owner==='enemy',count=Math.min(5,Math.max(1,Math.ceil(cell.soldiers/2)));return <group>{Array.from({length:count}).map((_,i)=><Actor key={i} file={cfg.role} action={cfg.action} enemy={enemy} phase={i*1.1} position={[(i%3)*.52-.52,.28,Math.floor(i/3)*.52-.35]}/>)}<Model file={cfg.resource} height={.23} position={[.78,.22,.52]}/><Model file={enemy?O_QUAN_ASSETS.props.redFlag:O_QUAN_ASSETS.props.blueFlag} height={.72} position={[-.86,.2,-.52]}/></group>}
function DanTile({tile,cell,selected,onSelect}:{tile:BoardTile;cell:Cell;selected:boolean;onSelect:(id:number)=>void}){const {scene}=useGLTF(assetUrl(tile.asset)),[hover,setHover]=useState(false),enemy=cell.owner==='enemy';const root=useMemo(()=>scene.clone(true),[scene]);const click=(event:ThreeEvent<MouseEvent>)=>{event.stopPropagation();if(!enemy)onSelect(cell.id)};return <group position={tile.position} rotation={tile.rotation} onClick={click} onPointerEnter={e=>{e.stopPropagation();setHover(true);document.body.style.cursor=enemy?'default':'pointer'}} onPointerLeave={()=>{setHover(false);document.body.style.cursor='default'}}><primitive object={root}/><DynamicOccupants cell={cell}/>{selected&&<Selection enemy={enemy}/>}<Html position={[0,1.42,.9]} center distanceFactor={12} style={{pointerEvents:'none'}}><div className={`world-label cell-label ${enemy?'red':''} ${(hover||selected)?'visible':''}`}>{names[cell.building]} <b>{cell.soldiers}</b></div></Html></group>}
function QuanTile({tile,enemy}:{tile:BoardTile;enemy:boolean}){const {scene}=useGLTF(assetUrl(tile.asset)),root=useMemo(()=>scene.clone(true),[scene]);return <group position={tile.position} rotation={tile.rotation}><primitive object={root}/>{[-.7,-.35,0,.35,.7].map((z,i)=><Actor key={i} file={O_QUAN_ASSETS.characters.elite} action="guard" enemy={enemy} phase={i} position={[-.9,.25,z]}/>)}<Model file={enemy?O_QUAN_ASSETS.props.redFlag:O_QUAN_ASSETS.props.blueFlag} height={1.2} position={[.7,.22,-.7]}/><Html position={[0,2.2,0]} center><div className={`world-label castle-label ${enemy?'red':''}`}>{enemy?'ĐỊCH THÀNH':'ĐẠI THÀNH'}</div></Html></group>}
function March({path,onDone}:{path:number[];onDone:()=>void}){const ref=useRef<THREE.Group>(null),start=useRef(performance.now());useFrame(()=>{if(!ref.current)return;const p=Math.min(path.length-1,(performance.now()-start.current)/360),i=Math.min(path.length-2,Math.floor(p)),t=p-i,a=new THREE.Vector3(...tilePosition(path[i])),b=new THREE.Vector3(...tilePosition(path[i+1]));ref.current.position.lerpVectors(a,b,t);ref.current.position.y=.45+Math.sin(t*Math.PI)*.3;ref.current.rotation.y=Math.atan2(b.x-a.x,b.z-a.z);if(p>=path.length-1)onDone()});return <group ref={ref}>{[-.18,0,.18].map((x,i)=><Actor key={i} file={O_QUAN_ASSETS.characters.soldier} action="train" enemy={false} phase={i} position={[x,0,(i%2)*.14]}/>)}</group>}
function WaterWorld(){return <group><mesh rotation={[-Math.PI/2,0,0]} position={[0,-.08,0]} receiveShadow><planeGeometry args={[42,28]}/><meshStandardMaterial color="#719b96" roughness={.32} metalness={.06}/></mesh><Model file={O_QUAN_ASSETS.props.boat} height={.34} position={[-3,-.01,0]}/><Model file={O_QUAN_ASSETS.props.boat} height={.28} position={[3.4,-.01,.2]} rotation={[0,Math.PI,0]}/><Model file={O_QUAN_ASSETS.props.gong} height={.38} position={[0,.02,0]}/></group>}
function Scene({cells,selected,onSelect}:{cells:Cell[];selected:number|null;onSelect:(id:number)=>void}){const previous=useRef(cells),[march,setMarch]=useState<{key:number;path:number[]}|null>(null);useEffect(()=>{const old=previous.current,source=old.findIndex((c,i)=>c.soldiers>cells[i].soldiers&&cells[i].soldiers===0);if(source>=0){const gains=cells.map((c,i)=>c.soldiers-old[i].soldiers),count=gains.filter(n=>n>0).length,cw=Array.from({length:count+1},(_,i)=>(source+i)%10),ccw=Array.from({length:count+1},(_,i)=>(source-i+10)%10),score=(p:number[])=>p.reduce((n,id)=>n+Math.max(0,gains[id]),0);setMarch({key:Date.now(),path:score(cw)>=score(ccw)?cw:ccw})}previous.current=cells.map(c=>({...c}))},[cells]);return <><color attach="background" args={['#839891']}/><fog attach="fog" args={['#839891',20,38]}/><ambientLight intensity={1.25}/><hemisphereLight args={['#e8e4cf','#53452f',1.4]}/><directionalLight position={[-8,14,9]} intensity={2.6} castShadow shadow-mapSize={[2048,2048]}/><WaterWorld/>{BOARD_LAYOUT.filter(t=>typeof t.id==='number').map(tile=><DanTile key={tile.id} tile={tile} cell={cells[tile.id as number]} selected={selected===tile.id} onSelect={onSelect}/>)}<QuanTile tile={BOARD_LAYOUT.find(t=>t.id==='player')!} enemy={false}/><QuanTile tile={BOARD_LAYOUT.find(t=>t.id==='enemy')!} enemy/>{march&&<March key={march.key} path={march.path} onDone={()=>setMarch(null)}/>}<ContactShadows position={[0,.12,0]} scale={28} opacity={.55} blur={2.5}/><Environment preset="forest"/><OrbitControls makeDefault target={[0,.3,0]} minPolarAngle={.58} maxPolarAngle={1.08} minDistance={4.5} maxDistance={32} zoomSpeed={1.15} rotateSpeed={.55} enableDamping dampingFactor={.08} enablePan={false}/></>}
export default function Board3D(props:{cells:Cell[];selected:number|null;onSelect:(id:number)=>void}){return <Canvas shadows dpr={[1,1.5]} camera={{position:[0,9,12],fov:38}}><Scene {...props}/></Canvas>}

const preload=[...Object.values(O_QUAN_ASSETS.board),...Object.values(O_QUAN_ASSETS.characters),...Object.values(O_QUAN_ASSETS.props),...Object.values(O_QUAN_ASSETS.resources)]
preload.forEach(file=>useGLTF.preload(assetUrl(file)))
